import type { Metadata } from "next";
import "./globals.css";
import { prozaLibre } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prozaLibre.className} overflow-x-hidden bg-[#FDF7EC]`}
      >
        {children}
      </body>
    </html>
  );
}
