import type { Metadata } from "next";
import "./globals.css";
import { prozaLibre } from "@/fonts/fonts";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prozaLibre.className} overflow-x-hidden bg-[#FDF7EC]`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
